### ISSUE TITLE
cb_tools package

### ISSUE THREAD

**Issue by eliauk07yz** [xingyu-liu/cerebellum_grad_dev#1]
Recently, I read your article "A multifaceted gradient in human cerebellum of structural and functional development" and found it very meaningful. I saw that you disclosed the code. This is very helpful for us, but it requires the package ‘import cb_tools’, which is not found in your github, is it convenient to share this code? Thank you very much

**Comment by xingyu-liu** [comment]
Sorry for the oversight. The code has now been uploaded. Thank you for bringing this up!
Best,
Xingyu
